services:
  openlist-rclone:
    image: ghcr.io/workerspages/openlist-rclone:latest
    container_name: openlist-rclone
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
      - ./host:/opt/host:ro # 映射宿主机目录至容器内，用于本地与网盘间的文件传输
    environment:
      - TZ=Asia/Shanghai
      - SWAP_SIZE_MB=512
      
      # Web 控制台登录凭据
      - WEB_USERNAME=admin
      - WEB_PASSWORD=admin
      
      # openList 管理员凭据
      - OPENLIST_ADMIN_USERNAME=admin
      - OPENLIST_ADMIN_PASSWORD=admin
      
      # 高级变量 (PaaS 无状态环境自动备份配置)
      # 方式一：结构化配置（推荐）
      # - STORAGE_TYPE=s3
      # - S3_ENDPOINT=https://xxx.r2.cloudflarestorage.com
      # - S3_ACCESS_KEY=your_ak
      # - S3_SECRET_KEY=your_sk
      # - S3_BUCKET=your_bucket
      # - S3_REGION=auto
      # - S3_PATH=openlist-rclone
      
      # 方式二：标准网址格式或底层语法（与方式一二选一即可）
      # - SYNC_DEST=s3://AK:SK@xxx.r2.cloudflarestorage.com/bucket
      
      # [主从架构] 自动同步外部存储的时间间隔（分钟）
      # - 主节点（Primary）: 设置大于0的值（如 5），自动定期推送更改到网盘。
      # - 从节点（Secondary）: 设置为 0，启用只读模式。容器启动时拉取一次配置，但**永不推送**（即使在关机时），彻底防止多节点互相覆盖数据。
      - SYNC_INTERVAL=5
      
      # 配置后定时任务执行完成时会自动发送推送通知
      - BARK_URL=https://api.day.app/yourkey
      
      # [可选] 自定义需要静默忽略的错误关键字（用英文逗号分隔），包含这些关键字的错误将被当做成功记录，且不发送失败报警
      - IGNORE_ERRORS=object not found,409 Conflict,Method Not Allowed
